name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build debug
        run: |
          ./gradlew clean zipDebug
          mkdir debug
          unzip module/release/Audit-Patch-*-debug.zip -d debug

      - name: Upload debug
        uses: actions/upload-artifact@v4
        with:
          name: Audit-Patch-debug
          path: "./debug/*"

      - name: Build release
        run: |
          ./gradlew clean zipRelease
          mkdir release
          unzip module/release/Audit-Patch-*-release.zip -d release

      - name: Upload release
        uses: actions/upload-artifact@v4
        with:
          name: Audit-Patch-release
          path: "./release/*"
